### PR TITLE
implement fail_because

### PR DESCRIPTION
**Pull request by MggMuggins**
Macro for failing for a reason, as well as printing the program name.

Don't merge this.

### CODE REVIEW

**Comment by goyox86** [comment]
I like it but I think we could do something in here https://github.com/redox-os/libextra/blob/master/src/option.rs#L9.

Also create a `ResultExt` if it's not there. 

So we can do:

```rust
let user = get_user_by_name("user").unwrap_or_exit();
```
Inside of that `unwrap_or_exit` will be some of what you are doing here.

At the end what we want to save is the very repetitive lines of passing the same almost identical closure printing the error and exiting the process. 

BTW we can do those two lines with `fail!` in here https://github.com/redox-os/libextra/blob/master/src/option.rs#L42

**Comment by MggMuggins** [comment]
Yes, but fail! doesn't print the name of the executable. We can also do that with `unwrap_or_exit()` if we'd like. I don't think I have a preference, although a return code specifier is a must in either case. Do what you'd like.

**Comment by goyox86** [comment]
Just to elaborate on why I'm leaning to something `unwrap_or_exit`. 

I think it's a good compromise between reusability and not tying it to much to be useful on the context of a utility. This crate is kind of general AFAIK and the extensions as far as I see are meant to be used without assuming any context. 

As much as I like that we could do as you are doing here by determining the name of the tool, that would couple it to that context only. So I would still opt for passing the name of the utility, and the status code. Also, sometimes we might want to use a different for the tool name other than the auto guess. 

I think with `unwrap_or_exit` we would accomplish our objectives of: getting rid of the closure, print the error and exit with the status.

I know you kind of agreed already but I thought it's was worth explaining why I'm advocating for something along the lines of `unwrap_or_exit`.

**Comment by MggMuggins** [comment]
You've got a solid argument. I would tend to agree However, the program name is still something I'd like to advocate more for before we go much farther:

While I was browsing the source tree for coreutils, I saw a lot of unstandard error reporting. This is of course, by the very nature of what we're trying to do, a bit of a moot point, because this function _should_ be able to more or less remove all of that. However, looking at it from the position of the end user (usually a sysadmin), I would say that accuracy regarding the error's perpetrator is important. Take this scenario:

A sysadmin has his server set up in such a way that he's renamed some of the userutils (no idea why this would happen, but better be safe). If he's writing a script, an error from "getty" might not make sense given the context of his server. Having error reports using the invoked argument instead of the hard-coded string may be a huge saver of time for debugging scripts.

I'm not sure how localization works with OS's, since I'm American, but that's another something to consider when doing error reporting.

As for implementing things, I think it's still a good idea to be _able_ to specify that. It's a shame there isn't function overloading, that would make things a lot easier, but I would say it's probably doable...

**Pull request closed without merging**
